export const Colors = {
  primary:        '#6C5A8E',
  primaryDark:    '#5a4976',
  primaryLight:   '#8b7aa8',
  primaryMuted:   '#D4C4E8',
  background:     '#EDE6F5',
  card:           '#FFFFFF',
  textPrimary:    '#1F2937',
  textSecondary:  '#374151',
  textMuted:      '#6B7280',
  topicTag:       '#EDE6F5',
  topicTagText:   '#6C5A8E',
  emotionTag:     '#FFF7ED',
  emotionTagText: '#EA580C',
  canChange:      '#E1F5EE',
  canChangeText:  '#0F6E56',
  cannotChange:   '#FAEEDA',
  danger:         '#FF6B6B',
} as const;
